
# local-profile 
#
# Creates ~/.local/etc/profile script that sources *.sh files at `~/.local/etc/profile.d/` allowing to modify env, PATH, etc.
[local-profile.files]
"config/.local/etc/profile" = "~/.local/etc/profile"
"config/.profile" = "~/.profile"

[zsh]
depends = ["nerd-fonts"]
[zsh.files]
"config/.zshrc" = "~/.zshrc"

[zsh-autosuggestions]
depends = ["zsh"]

[zsh-syntax-highlighting]
depends = ["zsh"]

[cargo]
depends = ["local-profile"]

[cargo.files]
"config/.local/etc/profile.d/cargo.sh" = "~/.local/etc/profile.d/cargo.sh"
"config/.cargo/config.toml" = "~/.cargo/config.toml"

[sccache]
depends = ["cargo"]

[zoxide]
depends = ["cargo"]

[starship]
depends = ["cargo", "nerd-fonts"]

# Fonts
[nerd-fonts]
depends = []

# Virtual package for shell
[shell]
depends = [
    "zsh",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
    "zoxide",
    "starship",
    "local-profile",
]
