
# local-profile 
#
# Creates ~/.local/etc/profile script that sources *.sh files at `~/.local/etc/profile.d/` allowing to modify env, PATH, etc.
[local-profile.files]
"config/.local/etc/profile" = "~/.local/etc/profile"
"config/.profile" = "~/.profile"

[zsh]
depends = ["nerd-fonts"]
[zsh.files]
"config/.zshrc" = "~/.zshrc"

[zsh-autosuggestions]
depends = ["zsh"]

[zsh-syntax-highlighting]
depends = ["zsh"]

[cargo]
depends = ["local-profile"]

[cargo.files]
"config/.local/etc/profile.d/cargo.sh" = "~/.local/etc/profile.d/cargo.sh"
"config/.cargo/config.toml" = "~/.cargo/config.toml"

[sccache]
depends = ["cargo"]

[zoxide]
depends = ["cargo"]

[starship]
depends = ["cargo", "nerd-fonts"]

[bat]
depends = ["cargo"]

[git.files]
"config/.gitconfig" = "~/.gitconfig"

[git.variables]
# Optional vars:
# email - email address
# git_name - user name used for git
# git_signingkey - path to key to sign
git_editor = "core --wait"

[dust]
depends = ["cargo"]

[hyperfine]
depends = ["cargo"]

[navi]
depends = ["cargo"]

[spell-check]
depends = []

[user-python]
depends = ["local-profile"]

[user-python.files]
"config/.local/etc/profile.d/user-python.sh" = "~/.local/etc/profile.d/user-python.sh"


# Fonts
[nerd-fonts]
depends = []

[cjk-fonts]
depends = []

# Hardware specific
# Defines env for ROCm
[amd-rx6700xt-rocm]
depends = ["local-profile"]

[amd-rx6700xt-rocm.files]
"config/.local/etc/profile.d/amd-rx6700xt-rocm.sh" = "~/.local/etc/profile.d/amd-rx6700xt-rocm.sh"

# Virtual package for shell
[shell]
depends = [
    "zsh",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
    "zoxide",
    "starship",
    "local-profile",
]

[essential]
depends = [
    "shell",
    "cjk-fonts",
    "rust-utils",
    "spell-check",
    "git",
    "user-python",
]


[rust-utils]
depends = ["bat", "dust", "hyperfine", "navi"]
