
# local-profile 
#
# Creates ~/.local/etc/profile script that sources *.sh files at `~/.local/etc/profile.d/` allowing to modify env, PATH, etc.
[local-profile.files]
"config/.local/etc/profile" = "~/.local/etc/profile"
"config/.profile" = "~/.profile"

[zsh]
depends = ["nerd-fonts"]
[zsh.files]
"config/.zshrc" = "~/.zshrc"

[zsh-autosuggestions]
depends = ["zsh"]

[zsh-syntax-highlighting]
depends = ["zsh"]

[cargo]
depends = ["local-profile"]

[cargo.files]
"config/.local/etc/profile.d/cargo.sh" = "~/.local/etc/profile.d/cargo.sh"
"config/.cargo/config.toml" = "~/.cargo/config.toml"

[sccache]
depends = ["cargo", "local-profile"]

[sccache.files]
"config/.local/etc/profile.d/ccache.sh" = "~/.local/etc/profile.d/ccache.sh"

# Override ccache
[sccache.files."config/.local/bin/ccache"]
type = "symbolic"
target = "~/.local/bin/ccache"
if = "dotter.packages.ccache"

[zoxide]
depends = ["cargo"]

[starship]
depends = ["cargo", "nerd-fonts", "cpp-tools"]

[bat]
depends = ["cargo"]

[git.files]
"config/.gitconfig" = "~/.gitconfig"

[git.variables]
# Optional vars:
# email - email address
# git_name - user name used for git
# git_signingkey - path to ssh key to sign
git_editor = "code --wait"

[dust]
depends = ["cargo"]

[hyperfine]
depends = ["cargo"]

[navi]
depends = ["cargo"]

[spell-check]
depends = []

[user-python]
depends = ["local-profile"]

[user-python.files]
"config/.local/etc/profile.d/user-python.sh" = "~/.local/etc/profile.d/user-python.sh"

[deepfilternet.files]
"config/.config/pipewire/filter-chain.conf" = "~/.config/pipewire/filter-chain.conf"
"config/.config/pipewire/filter-chain.conf.d/deepfilternet.conf" = "~/.config/pipewire/filter-chain.conf.d/deepfilternet.conf"

[cpp-tools]

[ccache]
depends = ["cpp-tools"]

[ccache.files]
"config/.ccache/ccache.conf" = "~/.ccache/ccache.conf"

# Systemd unit to mount disks
[systemd.files."config/.config/systemd/user/mount-by-label@.service"]
type = "symbolic"
target = "~/.config/systemd/user/mount-by-label@.service"

# Systemd unit to add ssh keys to ssh-agent
[systemd.files]
"config/.config/systemd/user/ssh-add@.service" = "~/.config/systemd/user/ssh-add@.service"

[kde-ssh]
depends = ["local-profile"]

[kde-ssh.files]
"config/.local/etc/profile.d/kde-ssh.sh" = "~/.local/etc/profile.d/kde-ssh.sh"

[flatpak]
depends = []

[gamemode.files]
"config/.config/gamemode.ini" = "~/.config/gamemode.ini"

[mangohud.files]
"config/.config/MangoHud/MangoHud.conf" = "~/.config/MangoHud/MangoHud.conf"
"packages/mangohud/common/post_deploy.tmpl.sh" = "packages/mangohud/common/post_deploy.generated.sh"

[gamescope]
depends = []

# Fonts
[nerd-fonts]
depends = []

[cjk-fonts]
depends = []

# Hardware specific
# Defines env for ROCm
[amd-rx6700xt-rocm]
depends = ["local-profile"]

[amd-rx6700xt-rocm.files]
"config/.local/etc/profile.d/amd-rx6700xt-rocm.sh" = "~/.local/etc/profile.d/amd-rx6700xt-rocm.sh"

# Virtual package for shell
[shell]
depends = [
    "zsh",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
    "zoxide",
    "starship",
    "local-profile",
]

[essential]
depends = [
    "shell",
    "cjk-fonts",
    "rust-utils",
    "spell-check",
    "git",
    "user-python",
]

[gaming]
depends = ["gamemode", "mangohud", "gamescope"]


[rust-utils]
depends = ["bat", "dust", "hyperfine", "navi"]
